[server]
enableStaticServing = true
maxUploadSize = 1024
[theme]
font = "Times New Roman"
headingFont = "Times New Roman"
codeFont = "monospace"
[theme.sidebar]
font = "Times New Roman"
headingFont = "Times New Roman"
codeFont = "monospace"
